### ISSUE TITLE
Cannot create new board: HTTP 403

### ISSUE THREAD

**Issue by pztrn** [majestrate/nntpchan#179]
## info

git revision / version: srnd-3.1.0-34ce6f8

OS: Debian 10

Architecture: amd64

## problem

Can't create board via /mod/. Gives HTTP 403.

## backtrace / error messages

Error messages: no

Backtrace: no

**Comment by majestrate** [comment]
boards are created via /new/
the /mod/ endpoint is for deleting posts when authenticated with a mod's key

**Comment by pztrn** [comment]
Thanks, yet, via /new/:

```
goroutine 64 [running]:
net/http.(*conn).serve.func1(0xc00037a6e0)
	/usr/lib/go-1.11/src/net/http/server.go:1746 +0xd0
panic(0x93eec0, 0xe2a3d0)
	/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
srnd.(*httpFrontend).handle_postform(0xc00047b380, 0xa83c00, 0xc000362000, 0xc000218300, 0xc00023a18b, 0x14, 0xc000130100)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:558 +0x2383
srnd.httpFrontend.handle_poster(0xa87e20, 0xc0002e6000, 0xc000312000, 0xc0001461a0, 0xa87d20, 0xc0000a0048, 0xc00013a8a5, 0xa, 0xc00026c105, 0x19, ...)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:972 +0x2c0
srnd.httpFrontend.handle_poster-fm(0xa83c00, 0xc000362000, 0xc000218300)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:1458 +0x91
net/http.HandlerFunc.ServeHTTP(0xc0003ed500, 0xa83c00, 0xc000362000, 0xc000218300)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
srnd/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000312000, 0xa83c00, 0xc000362000, 0xc000218300)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/vendor/github.com/gorilla/mux/mux.go:114 +0xe0
net/http.serverHandler.ServeHTTP(0xc0000948f0, 0xa83c00, 0xc000362000, 0xc000218100)
	/usr/lib/go-1.11/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc00037a6e0, 0xa846c0, 0xc0000621c0)
	/usr/lib/go-1.11/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/lib/go-1.11/src/net/http/server.go:2851 +0x2f5
2019/08/31 03:45:05 get locale en
2019/08/31 03:45:22 http: panic serving [208:168f:e4f9:647:d111:591b:972f:6e51]:54510: runtime error: invalid memory address or nil pointer dereference
goroutine 138 [running]:
net/http.(*conn).serve.func1(0xc0004f2000)
	/usr/lib/go-1.11/src/net/http/server.go:1746 +0xd0
panic(0x93eec0, 0xe2a3d0)
	/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
srnd.(*httpFrontend).handle_postform(0xc000073200, 0xa83c00, 0xc0003627e0, 0xc000218b00, 0xc0002ec96b, 0x14, 0xc000130100)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:558 +0x2383
srnd.httpFrontend.handle_poster(0xa87e20, 0xc0002e6000, 0xc000312000, 0xc0001461a0, 0xa87d20, 0xc0000a0048, 0xc00013a8a5, 0xa, 0xc00026c105, 0x19, ...)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:972 +0x2c0
srnd.httpFrontend.handle_poster-fm(0xa83c00, 0xc0003627e0, 0xc000218b00)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:1458 +0x91
net/http.HandlerFunc.ServeHTTP(0xc0003ed500, 0xa83c00, 0xc0003627e0, 0xc000218b00)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
srnd/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000312000, 0xa83c00, 0xc0003627e0, 0xc000218b00)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/vendor/github.com/gorilla/mux/mux.go:114 +0xe0
net/http.serverHandler.ServeHTTP(0xc0000948f0, 0xa83c00, 0xc0003627e0, 0xc0004f4600)
	/usr/lib/go-1.11/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0004f2000, 0xa846c0, 0xc0002c6780)
	/usr/lib/go-1.11/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/lib/go-1.11/src/net/http/server.go:2851 +0x2f5
2019/08/31 03:45:22 http: panic serving [208:168f:e4f9:647:d111:591b:972f:6e51]:54531: runtime error: invalid memory address or nil pointer dereference
goroutine 338 [running]:
net/http.(*conn).serve.func1(0xc0000a81e0)
	/usr/lib/go-1.11/src/net/http/server.go:1746 +0xd0
panic(0x93eec0, 0xe2a3d0)
	/usr/lib/go-1.11/src/runtime/panic.go:513 +0x1b9
srnd.(*httpFrontend).handle_postform(0xc000073380, 0xa83c00, 0xc0003628c0, 0xc000218e00, 0xc0002ecabb, 0x14, 0xc000130100)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:558 +0x2383
srnd.httpFrontend.handle_poster(0xa87e20, 0xc0002e6000, 0xc000312000, 0xc0001461a0, 0xa87d20, 0xc0000a0048, 0xc00013a8a5, 0xa, 0xc00026c105, 0x19, ...)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:972 +0x2c0
srnd.httpFrontend.handle_poster-fm(0xa83c00, 0xc0003628c0, 0xc000218e00)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/frontend_http.go:1458 +0x91
net/http.HandlerFunc.ServeHTTP(0xc0003ed500, 0xa83c00, 0xc0003628c0, 0xc000218e00)
	/usr/lib/go-1.11/src/net/http/server.go:1964 +0x44
srnd/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc000312000, 0xa83c00, 0xc0003628c0, 0xc000218e00)
	/home/nntpchan/nntpchan/contrib/backends/srndv2/src/srnd/vendor/github.com/gorilla/mux/mux.go:114 +0xe0
net/http.serverHandler.ServeHTTP(0xc0000948f0, 0xa83c00, 0xc0003628c0, 0xc000218c00)
	/usr/lib/go-1.11/src/net/http/server.go:2741 +0xab
net/http.(*conn).serve(0xc0000a81e0, 0xa846c0, 0xc0000a4700)
	/usr/lib/go-1.11/src/net/http/server.go:1847 +0x646
created by net/http.(*Server).Serve
	/usr/lib/go-1.11/src/net/http/server.go:2851 +0x2f5
```

**Comment by majestrate** [comment]
oofff, this is via ipv6?

**Comment by pztrn** [comment]
Yes, and solved this problem :) It was about frontend.domain, set this to internal ipv4 and everything works.

I'm gonna test nntpchan in Yggdrasil with friends :)

**Comment by majestrate** [comment]
cool, if you want to peer into the main i have one up at `201:880b:d0b9:a0a5:aac6:907b:7072:825a` port 1199 for nntp

**Comment by majestrate** [comment]
it crashes because the domain was not set and the session store errors, added 12709d3 to try and catch that.

**Comment by pztrn** [comment]
Why not? How to contant with you in private?

**Comment by majestrate** [comment]
email via jeff@i2p.rocks or xmpp jeff@i2p.rocks

**Comment by majestrate** [comment]
would love to see more yggdrasil servers for sure. let me know if this is fixed with that commit.

**Comment by majestrate** [comment]
pretty sure i can close this now
